openapi: 3.0.2
info:
  title: FDK service harvester
  description: fdk-public-service-harvester will harvest catalogs of public services (CPSV) according to the DCAT-AP-NO v2 specification.
  version: '1.0'
  contact:
    name: Digitaliseringsdirektoratet
    url: 'https://fellesdatakatalog.digdir.no'
    email: fellesdatakatalog@digdir.no
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
tags:
  - name: cpsv-ap-no-services
    description: CPSV-AP-NO services
servers:
  - url: 'https://data.norge.no/public-services'
    description: Produksjonsmiljø
  - url: 'https://staging.fellesdatakatalog.digdir.no/public-services'
    description: Testmiljø
  - url: 'https://demo.fellesdatakatalog.digdir.no/public-services'
    description: Demomiljø
paths:
  /public-services:
    get:
      tags:
        - cpsv-ap-no-services
      description: Returnerer en liste av tjenester
      operationId: getServices
      parameters:
        - name: catalogrecords
          in: query
          description: Include FDK catalog records
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: OK
          content:
            text/turtle:
              schema:
                type: string
            text/n3:
              schema:
                type: string
            application/rdf+json:
              schema:
                type: string
            application/ld+json:
              schema:
                type: string
            application/rdf+xml:
              schema:
                type: string
            application/n-triples:
              schema:
                type: string
  '/public-services/{id}':
    get:
      tags:
        - cpsv-ap-no-services
      description: Returnerer en tjeneste med gitt id
      operationId: getServiceById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
        - name: catalogrecords
          in: query
          description: Include FDK catalog records
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: OK
          content:
            text/turtle:
              schema:
                type: string
            text/n3:
              schema:
                type: string
            application/rdf+json:
              schema:
                type: string
            application/ld+json:
              schema:
                type: string
            application/rdf+xml:
              schema:
                type: string
            application/n-triples:
              schema:
                type: string
        '404':
          description: Service with requested id does not exist
  '/update/meta':
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - cpsv-ap-no-services
      description: Updates stored catalog records with current meta data for services
      operationId: updateMetaData
      responses:
        '204':
          description: No Content

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: [ ]
