logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.apache.jena.riot: ERROR
server:
  port: 8080
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  data.mongodb.uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/publicServiceHarvester?authSource=admin&authMechanism=SCRAM-SHA-1
fuseki:
  unionGraphUri: ${FDK_FUSEKI_SERVICE_URI:http://fdk-fuseki-service:8080/fuseki}/harvested?graph=https://services.fellesdatakatalog.digdir.no
application:
  tmpHarvest: ${TMP_HARVEST:https://raw.githubusercontent.com/Informasjonsforvaltning/fdk-testdata/master/testdata/fdk-public-service-publisher.ttl}
  publicServiceHarvesterUri: ${FDK_BASE_URI:https://staging.fellesdatakatalog.digdir.no}/public-services
  harvestAdminRootUrl: ${HARVEST_ADMIN_ROOT_URL:http://fdk-harvest-admin:8080/api}

---
spring:
  profiles: develop
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  data.mongodb.uri: mongodb://admin:admin@localhost:27017/publicServiceHarvester?authSource=admin&authMechanism=SCRAM-SHA-1
fuseki:
  unionGraphUri: http://localhost:3030/fuseki/harvested?graph=https://services.fellesdatakatalog.digdir.no
application:
  tmpHarvest: https://raw.githubusercontent.com/Informasjonsforvaltning/fdk-testdata/master/testdata/fdk-public-service-publisher.ttl
  publicServiceHarvesterUri: https://staging.fellesdatakatalog.digdir.no/public-services
  harvestAdminRootUrl: https://admin-api.staging.fellesdatakatalog.digdir.no/api

---
spring:
  profiles: contract-test
  rabbitmq:
    host: localhost
    port: 5000
    username: admin
    password: admin
application:
  tmpHarvest: http://localhost:5000/fdk-public-service-publisher.ttl
  publicServiceHarvesterUri: http://localhost:5000/public-services
  harvestAdminRootUrl: http://localhost:5000/api
fuseki.unionGraphUri: http://localhost:5000/fuseki/harvested?graph=https://services.fellesdatakatalog.digdir.no
