logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.apache.jena.riot: ERROR
server:
  port: 8080
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  data.mongodb:
    host: ${MONGODB_HOST}
    username: ${MONGODB_USER}
    password: ${MONGODB_PASSWORD}
    authentication-database: ${MONGODB_AUTH}
    replica-set-name: ${MONGODB_REPLICASET}
    port: 27017
    database: publicServiceHarvester
    auto-index-creation: true
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: ${SSO_HOST:https://sso.staging.fellesdatakatalog.digdir.no}/auth/realms/fdk/protocol/openid-connect/certs
    issuer-uri: ${SSO_HOST:https://sso.staging.fellesdatakatalog.digdir.no}/auth/realms/fdk
application:
  organizationsUri: ${ORGANIZATION_CATALOG_URI:https://organization-catalog.staging.fellesdatakatalog.digdir.no}/organizations
  publicServiceHarvesterUri: ${FDK_BASE_URI:https://staging.fellesdatakatalog.digdir.no}/public-services
  harvestAdminRootUrl: ${HARVEST_ADMIN_ROOT_URL:http://new-harvest-admin:8080}
  harvestAdminApiKey: ${ADMIN_API_KEY}
  cors.originPatterns: "${CORS_ORIGIN_PATTERNS}"
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        info: ping
        health: ready
      exposure:
        include: health, info, prometheus
    tags:
      application: fdk-public-service-harvester
---
spring:
  config.activate.on-profile: develop
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  data.mongodb:
    host: localhost
    username: admin
    password: admin
    authentication-database: admin
    replica-set-name: null
application:
  publicServiceHarvesterUri: https://staging.fellesdatakatalog.digdir.no/public-services
  harvestAdminRootUrl: https://new-admin.staging.fellesdatakatalog.digdir.no
  harvestAdminApiKey: test-key
  cors.originPatterns: "*"

---
spring:
  config.activate.on-profile: contract-test
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: http://localhost:5050/auth/realms/fdk/protocol/openid-connect/certs
    issuer-uri: http://localhost:5050/auth/realms/fdk
  rabbitmq:
    host: localhost
    port: 5050
    username: admin
    password: admin
  data.mongodb:
    host: localhost
    username: testuser
    password: testpassword
    authentication-database: admin
    replica-set-name: null
application:
  organizationsUri: http://localhost:5050/organizations
  publicServiceHarvesterUri: http://localhost:5050/public-services
  harvestAdminRootUrl: http://localhost:5050
  harvestAdminApiKey: test-key
  cors.originPatterns: "*"
