logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.apache.jena.riot: ERROR
server:
  port: 8080
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  data.mongodb.uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/publicServiceHarvester?authSource=admin&authMechanism=SCRAM-SHA-1
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: ${SSO_HOST:https://sso.staging.fellesdatakatalog.digdir.no}/auth/realms/fdk/protocol/openid-connect/certs
    issuer-uri: ${SSO_HOST:https://sso.staging.fellesdatakatalog.digdir.no}/auth/realms/fdk
application:
  organizationsUri: ${ORGANIZATION_CATALOG_URI:https://organization-catalog.staging.fellesdatakatalog.digdir.no}/organizations
  publicServiceHarvesterUri: ${FDK_BASE_URI:https://staging.fellesdatakatalog.digdir.no}/public-services
  harvestAdminRootUrl: ${HARVEST_ADMIN_ROOT_URL:http://new-harvest-admin:8080}
management:
  endpoints:
    web:
      path-mapping:
        info: ping
      exposure:
        include: health, info, prometheus
    tags:
      application: fdk-public-service-harvester
---
spring:
  config.activate.on-profile: develop
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  data.mongodb.uri: mongodb://admin:admin@localhost:27017/publicServiceHarvester?authSource=admin&authMechanism=SCRAM-SHA-1
application:
  publicServiceHarvesterUri: https://staging.fellesdatakatalog.digdir.no/public-services
  harvestAdminRootUrl: https://new-admin.staging.fellesdatakatalog.digdir.no

---
spring:
  config.activate.on-profile: contract-test
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: http://localhost:5000/auth/realms/fdk/protocol/openid-connect/certs
    issuer-uri: http://localhost:5000/auth/realms/fdk
  rabbitmq:
    host: localhost
    port: 5000
    username: admin
    password: admin
application:
  organizationsUri: http://localhost:5000/organizations
  publicServiceHarvesterUri: http://localhost:5000/public-services
  harvestAdminRootUrl: http://localhost:5000
